# Generated by Django 5.2.6 on 2025-09-14 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('address', models.CharField(max_length=255)),
                ('phone_number', models.CharField(max_length=15)),
                ('working_time', models.CharField(max_length=50)),
                ('delivery_fee', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
    ]
