# Generated by Django 5.2.6 on 2025-09-14 09:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0001_initial'),
        ('restaurant', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bonus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('buy_count', models.IntegerField(default=1)),
                ('add', models.IntegerField(default=0)),
                ('banner_image_url', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='food',
            name='first_section',
        ),
        migrations.RemoveField(
            model_name='food',
            name='second_section',
        ),
        migrations.AddField(
            model_name='food',
            name='restaurant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='foods', to='restaurant.restaurant'),
        ),
        migrations.AddField(
            model_name='food',
            name='bonus_section',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='foods', to='food.bonus'),
        ),
    ]
