# Generated by Django 5.2.5 on 2025-09-29 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0002_bonus_remove_food_first_section_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='food',
            name='overall',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=9),
        ),
    ]
