# Generated by Django 5.2.5 on 2025-09-30 11:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0003_food_overall'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='food',
            name='overall',
        ),
    ]
