# Generated by Django 5.2.5 on 2025-09-29 12:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('food', '0003_food_overall'),
        ('restaurant', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Deliver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('preparing', 'Preparing'), ('delivering', 'Delivering'), ('delivered', 'Delivered'), ('canceled', 'Canceled')], default='preparing', max_length=255)),
                ('overall', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('destination', models.CharField(max_length=255)),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='delivers', to='restaurant.restaurant')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='delivers', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DeliverDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deliver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deliver_details', to='deliver.deliver')),
                ('food', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deliver_details', to='food.food')),
            ],
        ),
        migrations.AddField(
            model_name='deliver',
            name='deliver_detail',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='delivers', to='deliver.deliverdetail'),
        ),
    ]
